# Generated by Django 5.0.6 on 2024-06-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shepower', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default='Padma', on_delete=django.db.models.deletion.CASCADE, to='shepower.employee'),
            preserve_default=False,
        ),
    ]
