# Generated by Django 5.0.6 on 2024-06-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shepower', '0004_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
